In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([1,2,33,4,4,53])

array([ 1,  2, 33,  4,  4, 53])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((10,10) , dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
np.random.rand(10)

array([0.85031007, 0.4828125 , 0.04971872, 0.69557583, 0.41505025,
       0.93255524, 0.23858004, 0.21285267, 0.26906223, 0.55599435])

In [9]:
arr=np.random.randint(1,100,(3,3))

In [10]:
type(arr.shape)

tuple

In [11]:
print(arr.reshape(9,1,copy=True))
print(arr)

[[22]
 [35]
 [19]
 [49]
 [17]
 [80]
 [65]
 [ 4]
 [18]]
[[22 35 19]
 [49 17 80]
 [65  4 18]]


In [12]:
arr[:]

array([[22, 35, 19],
       [49, 17, 80],
       [65,  4, 18]], dtype=int32)

In [13]:
arr[:,-2:-1]

array([[35],
       [17],
       [ 4]], dtype=int32)

In [14]:
arr[1:3, 0:2]

array([[49, 17],
       [65,  4]], dtype=int32)

In [15]:
arr3=np.random.randint(1,100,(10,10))
arr3

array([[87, 79, 90, 45,  1, 29,  8, 68, 62, 62],
       [30, 97, 59,  7, 37, 25, 42, 38, 90, 15],
       [43, 43, 81, 29, 98, 93, 16, 35, 86, 10],
       [98, 26, 28, 75, 38, 68, 88, 25, 21,  2],
       [22, 29, 73, 14, 41, 47,  7, 72, 54, 26],
       [68, 57, 37, 46, 33, 59, 73, 60,  9, 61],
       [70, 13, 39, 24, 41, 77, 75, 22, 63, 37],
       [84, 92, 26, 28, 62, 91, 27, 20, 49, 56],
       [62, 61, 60, 59, 19, 90, 52, 74, 81, 80],
       [82, 82, 37, 76, 70, 24,  1, 57,  9, 26]], dtype=int32)

In [16]:
arr3[(arr3>50) | (arr3==67)]

array([87, 79, 90, 68, 62, 62, 97, 59, 90, 81, 98, 93, 86, 98, 75, 68, 88,
       73, 72, 54, 68, 57, 59, 73, 60, 61, 70, 77, 75, 63, 84, 92, 62, 91,
       56, 62, 61, 60, 59, 90, 52, 74, 81, 80, 82, 82, 76, 70, 57],
      dtype=int32)

In [17]:
arr3[0,0]

np.int32(87)

In [18]:
arr3[0, 5:10]

array([29,  8, 68, 62, 62], dtype=int32)

In [19]:
arr3[0:-2]

array([[87, 79, 90, 45,  1, 29,  8, 68, 62, 62],
       [30, 97, 59,  7, 37, 25, 42, 38, 90, 15],
       [43, 43, 81, 29, 98, 93, 16, 35, 86, 10],
       [98, 26, 28, 75, 38, 68, 88, 25, 21,  2],
       [22, 29, 73, 14, 41, 47,  7, 72, 54, 26],
       [68, 57, 37, 46, 33, 59, 73, 60,  9, 61],
       [70, 13, 39, 24, 41, 77, 75, 22, 63, 37],
       [84, 92, 26, 28, 62, 91, 27, 20, 49, 56]], dtype=int32)

In [20]:
arr3[::-1]

array([[82, 82, 37, 76, 70, 24,  1, 57,  9, 26],
       [62, 61, 60, 59, 19, 90, 52, 74, 81, 80],
       [84, 92, 26, 28, 62, 91, 27, 20, 49, 56],
       [70, 13, 39, 24, 41, 77, 75, 22, 63, 37],
       [68, 57, 37, 46, 33, 59, 73, 60,  9, 61],
       [22, 29, 73, 14, 41, 47,  7, 72, 54, 26],
       [98, 26, 28, 75, 38, 68, 88, 25, 21,  2],
       [43, 43, 81, 29, 98, 93, 16, 35, 86, 10],
       [30, 97, 59,  7, 37, 25, 42, 38, 90, 15],
       [87, 79, 90, 45,  1, 29,  8, 68, 62, 62]], dtype=int32)

In [21]:
arr3.max()

np.int32(98)

In [22]:
arr3.mean()

np.float64(49.6)

In [23]:
arr3.sum()

np.int64(4960)

In [24]:
arr3

array([[87, 79, 90, 45,  1, 29,  8, 68, 62, 62],
       [30, 97, 59,  7, 37, 25, 42, 38, 90, 15],
       [43, 43, 81, 29, 98, 93, 16, 35, 86, 10],
       [98, 26, 28, 75, 38, 68, 88, 25, 21,  2],
       [22, 29, 73, 14, 41, 47,  7, 72, 54, 26],
       [68, 57, 37, 46, 33, 59, 73, 60,  9, 61],
       [70, 13, 39, 24, 41, 77, 75, 22, 63, 37],
       [84, 92, 26, 28, 62, 91, 27, 20, 49, 56],
       [62, 61, 60, 59, 19, 90, 52, 74, 81, 80],
       [82, 82, 37, 76, 70, 24,  1, 57,  9, 26]], dtype=int32)