In [2]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
 arr=np.random.randint(0,10,(3,3))
 arr

array([[5, 8, 7],
       [3, 1, 4],
       [9, 9, 3]], dtype=int32)

In [6]:
np.add(arr,3)

array([[ 8, 11, 10],
       [ 6,  4,  7],
       [12, 12,  6]], dtype=int32)

In [7]:
np.subtract(arr,3)

array([[ 2,  5,  4],
       [ 0, -2,  1],
       [ 6,  6,  0]], dtype=int32)

In [8]:
np.multiply(arr,3)

array([[15, 24, 21],
       [ 9,  3, 12],
       [27, 27,  9]], dtype=int32)

In [9]:
np.divide(arr,3)

array([[1.66666667, 2.66666667, 2.33333333],
       [1.        , 0.33333333, 1.33333333],
       [3.        , 3.        , 1.        ]])

In [10]:
np.power(arr,2)

array([[25, 64, 49],
       [ 9,  1, 16],
       [81, 81,  9]], dtype=int32)

In [11]:
np.sqrt(arr)

array([[2.23606798, 2.82842712, 2.64575131],
       [1.73205081, 1.        , 2.        ],
       [3.        , 3.        , 1.73205081]])

In [12]:
np.dot(arr,arr)

array([[112, 111,  88],
       [ 54,  61,  37],
       [ 99, 108, 108]], dtype=int32)

In [13]:
np.cross(arr,arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [16]:
arr2= arr.reshape(1,9)
arr2

array([[5, 8, 7, 3, 1, 4, 9, 9, 3]], dtype=int32)

In [17]:
np.dot(arr,arr2)

ValueError: shapes (3,3) and (1,9) not aligned: 3 (dim 1) != 1 (dim 0)

In [18]:
np.cross(arr,arr2)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)