In [5]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
np.__version__
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([1,2,33,4,4,53])

array([ 1,  2, 33,  4,  4, 53])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros((10,10) , dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
np.random.rand(10)

array([0.75096147, 0.29518273, 0.3121996 , 0.21632962, 0.02088672,
       0.01971862, 0.9462011 , 0.44344324, 0.25293374, 0.36664492])

In [13]:
arr=np.random.randint(1,100,(3,3))

In [14]:
type(arr.shape)

tuple

In [15]:
print(arr.reshape(9,1,copy=True))
print(arr)

[[43]
 [27]
 [73]
 [66]
 [37]
 [87]
 [44]
 [71]
 [40]]
[[43 27 73]
 [66 37 87]
 [44 71 40]]


In [16]:
arr[:]

array([[43, 27, 73],
       [66, 37, 87],
       [44, 71, 40]], dtype=int32)

In [17]:
arr[:,-2:-1]

array([[27],
       [37],
       [71]], dtype=int32)

In [18]:
arr[1:3, 0:2]

array([[66, 37],
       [44, 71]], dtype=int32)

In [19]:
arr3=np.random.randint(1,100,(10,10))
arr3

array([[ 1, 20, 62, 34, 15, 17, 81, 82, 68, 97],
       [15, 13,  9, 20, 91, 86, 53, 80, 89,  9],
       [95, 80, 11, 42, 28, 42,  5, 39,  9, 29],
       [17, 76,  2, 39, 96,  7, 58, 67, 33, 58],
       [16, 69, 57,  7, 92, 15, 18, 20, 99, 89],
       [ 8, 34, 78, 48, 39, 95, 47, 87, 63, 59],
       [37, 46, 28, 47, 87, 87, 80, 14, 91, 12],
       [37, 60, 33, 37, 65, 79, 57, 65, 25, 36],
       [97, 57, 90, 85, 96, 92, 59, 28, 26, 92],
       [91, 87, 92, 73, 21, 29, 80, 76, 22, 16]], dtype=int32)

In [20]:
arr3[(arr3>50) | (arr3==67)]

array([62, 81, 82, 68, 97, 91, 86, 53, 80, 89, 95, 80, 76, 96, 58, 67, 58,
       69, 57, 92, 99, 89, 78, 95, 87, 63, 59, 87, 87, 80, 91, 60, 65, 79,
       57, 65, 97, 57, 90, 85, 96, 92, 59, 92, 91, 87, 92, 73, 80, 76],
      dtype=int32)

In [21]:
arr3[0,0]

np.int32(1)

In [22]:
arr3[0, 5:10]

array([17, 81, 82, 68, 97], dtype=int32)

In [23]:
arr3[0:-2]

array([[ 1, 20, 62, 34, 15, 17, 81, 82, 68, 97],
       [15, 13,  9, 20, 91, 86, 53, 80, 89,  9],
       [95, 80, 11, 42, 28, 42,  5, 39,  9, 29],
       [17, 76,  2, 39, 96,  7, 58, 67, 33, 58],
       [16, 69, 57,  7, 92, 15, 18, 20, 99, 89],
       [ 8, 34, 78, 48, 39, 95, 47, 87, 63, 59],
       [37, 46, 28, 47, 87, 87, 80, 14, 91, 12],
       [37, 60, 33, 37, 65, 79, 57, 65, 25, 36]], dtype=int32)

In [24]:
arr3[::-1]

array([[91, 87, 92, 73, 21, 29, 80, 76, 22, 16],
       [97, 57, 90, 85, 96, 92, 59, 28, 26, 92],
       [37, 60, 33, 37, 65, 79, 57, 65, 25, 36],
       [37, 46, 28, 47, 87, 87, 80, 14, 91, 12],
       [ 8, 34, 78, 48, 39, 95, 47, 87, 63, 59],
       [16, 69, 57,  7, 92, 15, 18, 20, 99, 89],
       [17, 76,  2, 39, 96,  7, 58, 67, 33, 58],
       [95, 80, 11, 42, 28, 42,  5, 39,  9, 29],
       [15, 13,  9, 20, 91, 86, 53, 80, 89,  9],
       [ 1, 20, 62, 34, 15, 17, 81, 82, 68, 97]], dtype=int32)

In [25]:
arr3.max()

np.int32(99)

In [26]:
arr3.mean()

np.float64(51.47)

In [27]:
arr3.sum()

np.int64(5147)