In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
np.__version__
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.array([1,2,33,4,4,53])

array([ 1,  2, 33,  4,  4, 53])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros((10,10) , dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
np.random.rand(10)

array([0.45932251, 0.83630233, 0.64344129, 0.74475723, 0.46953356,
       0.76121673, 0.56882681, 0.7706056 , 0.78017274, 0.82281408])

In [11]:
arr=np.random.randint(1,100,(3,3))

In [12]:
type(arr.shape)

tuple

In [13]:
print(arr.reshape(9,1,copy=True))
print(arr)

[[66]
 [37]
 [81]
 [72]
 [52]
 [28]
 [44]
 [57]
 [71]]
[[66 37 81]
 [72 52 28]
 [44 57 71]]


In [14]:
arr[:]

array([[66, 37, 81],
       [72, 52, 28],
       [44, 57, 71]], dtype=int32)

In [15]:
arr[:,-2:-1]

array([[37],
       [52],
       [57]], dtype=int32)

In [16]:
arr[1:3, 0:2]

array([[72, 52],
       [44, 57]], dtype=int32)

In [17]:
arr3=np.random.randint(1,100,(10,10))
arr3

array([[98, 98, 12, 31, 46, 14, 80, 68, 12, 69],
       [35,  1, 83, 38, 33, 13, 24, 93, 61, 16],
       [97, 67, 97, 46, 96, 34, 55, 97, 23, 89],
       [88, 27, 15, 24, 94, 64, 66, 34, 35, 31],
       [14,  9, 57, 58, 17, 33, 87, 67, 95, 98],
       [34, 96, 41, 93, 61, 83, 10, 31, 37, 66],
       [44, 80, 12, 58, 25, 35, 22, 29, 37, 78],
       [53, 72,  9, 38, 56, 98, 63, 24, 88, 76],
       [12, 70, 88, 70, 14, 95, 93, 19, 57, 83],
       [61, 45, 93, 83, 88, 68, 62, 31, 84, 75]], dtype=int32)

In [18]:
arr3[(arr3>50) | (arr3==67)]

array([98, 98, 80, 68, 69, 83, 93, 61, 97, 67, 97, 96, 55, 97, 89, 88, 94,
       64, 66, 57, 58, 87, 67, 95, 98, 96, 93, 61, 83, 66, 80, 58, 78, 53,
       72, 56, 98, 63, 88, 76, 70, 88, 70, 95, 93, 57, 83, 61, 93, 83, 88,
       68, 62, 84, 75], dtype=int32)

In [19]:
arr3[0,0]

np.int32(98)

In [20]:
arr3[0, 5:10]

array([14, 80, 68, 12, 69], dtype=int32)

In [21]:
arr3[0:-2]

array([[98, 98, 12, 31, 46, 14, 80, 68, 12, 69],
       [35,  1, 83, 38, 33, 13, 24, 93, 61, 16],
       [97, 67, 97, 46, 96, 34, 55, 97, 23, 89],
       [88, 27, 15, 24, 94, 64, 66, 34, 35, 31],
       [14,  9, 57, 58, 17, 33, 87, 67, 95, 98],
       [34, 96, 41, 93, 61, 83, 10, 31, 37, 66],
       [44, 80, 12, 58, 25, 35, 22, 29, 37, 78],
       [53, 72,  9, 38, 56, 98, 63, 24, 88, 76]], dtype=int32)

In [22]:
arr3[::-1]

array([[61, 45, 93, 83, 88, 68, 62, 31, 84, 75],
       [12, 70, 88, 70, 14, 95, 93, 19, 57, 83],
       [53, 72,  9, 38, 56, 98, 63, 24, 88, 76],
       [44, 80, 12, 58, 25, 35, 22, 29, 37, 78],
       [34, 96, 41, 93, 61, 83, 10, 31, 37, 66],
       [14,  9, 57, 58, 17, 33, 87, 67, 95, 98],
       [88, 27, 15, 24, 94, 64, 66, 34, 35, 31],
       [97, 67, 97, 46, 96, 34, 55, 97, 23, 89],
       [35,  1, 83, 38, 33, 13, 24, 93, 61, 16],
       [98, 98, 12, 31, 46, 14, 80, 68, 12, 69]], dtype=int32)

In [23]:
arr3.max()

np.int32(98)

In [24]:
arr3.mean()

np.float64(54.79)

In [25]:
arr3.sum()

np.int64(5479)

In [26]:
arr3

array([[98, 98, 12, 31, 46, 14, 80, 68, 12, 69],
       [35,  1, 83, 38, 33, 13, 24, 93, 61, 16],
       [97, 67, 97, 46, 96, 34, 55, 97, 23, 89],
       [88, 27, 15, 24, 94, 64, 66, 34, 35, 31],
       [14,  9, 57, 58, 17, 33, 87, 67, 95, 98],
       [34, 96, 41, 93, 61, 83, 10, 31, 37, 66],
       [44, 80, 12, 58, 25, 35, 22, 29, 37, 78],
       [53, 72,  9, 38, 56, 98, 63, 24, 88, 76],
       [12, 70, 88, 70, 14, 95, 93, 19, 57, 83],
       [61, 45, 93, 83, 88, 68, 62, 31, 84, 75]], dtype=int32)

In [27]:
arr3

array([[98, 98, 12, 31, 46, 14, 80, 68, 12, 69],
       [35,  1, 83, 38, 33, 13, 24, 93, 61, 16],
       [97, 67, 97, 46, 96, 34, 55, 97, 23, 89],
       [88, 27, 15, 24, 94, 64, 66, 34, 35, 31],
       [14,  9, 57, 58, 17, 33, 87, 67, 95, 98],
       [34, 96, 41, 93, 61, 83, 10, 31, 37, 66],
       [44, 80, 12, 58, 25, 35, 22, 29, 37, 78],
       [53, 72,  9, 38, 56, 98, 63, 24, 88, 76],
       [12, 70, 88, 70, 14, 95, 93, 19, 57, 83],
       [61, 45, 93, 83, 88, 68, 62, 31, 84, 75]], dtype=int32)