In [2]:
!pip install numpy

In [3]:
import numpy as np

In [7]:
np.__version__
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([1,2,33,4,4,53])

array([ 1,  2, 33,  4,  4, 53])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros((10,10) , dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
np.random.rand(10)

array([0.15504294, 0.31710769, 0.81448308, 0.99504533, 0.73990157,
       0.07279019, 0.01411866, 0.76235141, 0.07500547, 0.240434  ])

In [38]:
arr=np.random.randint(1,100,(3,3))

In [37]:
type(arr.shape)

tuple

In [49]:
print(arr.reshape(9,1,copy=True))
print(arr)

[[73]
 [56]
 [52]
 [52]
 [11]
 [56]
 [65]
 [60]
 [31]]
[[73 56 52]
 [52 11 56]
 [65 60 31]]


In [50]:
arr[:]

array([[73, 56, 52],
       [52, 11, 56],
       [65, 60, 31]], dtype=int32)

In [53]:
arr[:,-2:-1]

array([[56],
       [11],
       [60]], dtype=int32)

In [57]:
arr[1:3, 0:2]

array([[52, 11],
       [65, 60]], dtype=int32)

In [70]:
arr3=np.random.randint(1,100,(10,10))
arr3

array([[48, 73, 97, 38, 27, 75, 21,  6, 37, 68],
       [90, 65, 24, 31, 23, 50,  3, 42, 26, 93],
       [79,  9, 76, 92, 78, 90, 40, 80,  9, 35],
       [86, 37,  6, 47, 55, 78, 61, 46, 43, 36],
       [98, 26, 81, 26, 11, 95, 21, 29, 83,  8],
       [55, 56, 70, 29, 80, 49, 38,  9, 60, 71],
       [75, 72, 80, 50, 25, 92, 85, 71, 42, 87],
       [13, 92, 70,  9, 16, 47, 43, 17, 80, 74],
       [93, 84, 82, 43,  6, 32, 97, 46, 70, 17],
       [ 8, 21, 98, 96, 77, 57, 47,  9, 15, 11]], dtype=int32)

In [ ]:
arr3[(arr3>50) | (arr3==67)]

array([67, 73, 69, 96, 96, 84, 60, 80, 79, 94, 86, 73, 59, 62, 95, 71, 89,
       62, 58, 64, 86, 90, 96, 69, 93, 88, 89, 64, 79, 71, 72, 88, 57, 96,
       84, 57, 72, 87, 73, 74, 93, 54, 58], dtype=int32)

In [66]:
arr3[0,0]

np.int32(67)

In [71]:
arr3[0, 5:10]

array([75, 21,  6, 37, 68], dtype=int32)

In [74]:
arr3[0:-2]

array([[48, 73, 97, 38, 27, 75, 21,  6, 37, 68],
       [90, 65, 24, 31, 23, 50,  3, 42, 26, 93],
       [79,  9, 76, 92, 78, 90, 40, 80,  9, 35],
       [86, 37,  6, 47, 55, 78, 61, 46, 43, 36],
       [98, 26, 81, 26, 11, 95, 21, 29, 83,  8],
       [55, 56, 70, 29, 80, 49, 38,  9, 60, 71],
       [75, 72, 80, 50, 25, 92, 85, 71, 42, 87],
       [13, 92, 70,  9, 16, 47, 43, 17, 80, 74]], dtype=int32)

In [79]:
arr3[::-1]

array([[ 8, 21, 98, 96, 77, 57, 47,  9, 15, 11],
       [93, 84, 82, 43,  6, 32, 97, 46, 70, 17],
       [13, 92, 70,  9, 16, 47, 43, 17, 80, 74],
       [75, 72, 80, 50, 25, 92, 85, 71, 42, 87],
       [55, 56, 70, 29, 80, 49, 38,  9, 60, 71],
       [98, 26, 81, 26, 11, 95, 21, 29, 83,  8],
       [86, 37,  6, 47, 55, 78, 61, 46, 43, 36],
       [79,  9, 76, 92, 78, 90, 40, 80,  9, 35],
       [90, 65, 24, 31, 23, 50,  3, 42, 26, 93],
       [48, 73, 97, 38, 27, 75, 21,  6, 37, 68]], dtype=int32)

In [ ]:
arr3.max()

array([98, 92, 98, 96, 80, 95, 97, 80, 83, 93], dtype=int32)

In [87]:
arr3.mean()

np.float64(51.64)