In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 11.8 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.6 MB 13.9 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 14.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 15.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 14.7 MB/s  0:00:00


In [2]:
import numpy as np

In [3]:
np.__version__
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([1,2,33,4,4,53])

array([ 1,  2, 33,  4,  4, 53])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((10,10) , dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
np.random.rand(10)

array([0.27900975, 0.9353955 , 0.05767018, 0.95212254, 0.35242497,
       0.78642338, 0.53823093, 0.95076091, 0.66751555, 0.98782499])

In [9]:
arr=np.random.randint(1,100,(3,3))

In [10]:
type(arr.shape)

tuple

In [11]:
print(arr.reshape(9,1,copy=True))
print(arr)

[[93]
 [60]
 [63]
 [86]
 [41]
 [23]
 [81]
 [ 4]
 [31]]
[[93 60 63]
 [86 41 23]
 [81  4 31]]


In [12]:
arr[:]

array([[93, 60, 63],
       [86, 41, 23],
       [81,  4, 31]], dtype=int32)

In [13]:
arr[:,-2:-1]

array([[60],
       [41],
       [ 4]], dtype=int32)

In [14]:
arr[1:3, 0:2]

array([[86, 41],
       [81,  4]], dtype=int32)

In [15]:
arr3=np.random.randint(1,100,(10,10))
arr3

array([[74, 53, 98, 80, 45, 87, 51, 11, 78, 40],
       [65, 93, 40, 14,  8, 88, 12, 79, 52, 61],
       [55, 53, 56, 73, 23, 65, 91,  5, 21, 62],
       [ 8, 60, 11, 70,  3, 76, 26, 63, 95, 61],
       [62, 49,  5, 34, 96, 19, 59, 73, 40, 90],
       [57, 96, 94, 67, 98, 12, 66, 62, 44, 97],
       [69, 46, 53, 18, 43, 73, 48, 73, 41, 42],
       [23, 20, 76, 81, 50, 64, 38, 30,  8, 13],
       [77, 15, 52, 53, 60, 49,  8, 50, 49, 49],
       [36, 79, 67,  3, 67, 97, 79, 90, 36, 47]], dtype=int32)

In [16]:
arr3[(arr3>50) | (arr3==67)]

array([74, 53, 98, 80, 87, 51, 78, 65, 93, 88, 79, 52, 61, 55, 53, 56, 73,
       65, 91, 62, 60, 70, 76, 63, 95, 61, 62, 96, 59, 73, 90, 57, 96, 94,
       67, 98, 66, 62, 97, 69, 53, 73, 73, 76, 81, 64, 77, 52, 53, 60, 79,
       67, 67, 97, 79, 90], dtype=int32)

In [17]:
arr3[0,0]

np.int32(74)

In [18]:
arr3[0, 5:10]

array([87, 51, 11, 78, 40], dtype=int32)

In [19]:
arr3[0:-2]

array([[74, 53, 98, 80, 45, 87, 51, 11, 78, 40],
       [65, 93, 40, 14,  8, 88, 12, 79, 52, 61],
       [55, 53, 56, 73, 23, 65, 91,  5, 21, 62],
       [ 8, 60, 11, 70,  3, 76, 26, 63, 95, 61],
       [62, 49,  5, 34, 96, 19, 59, 73, 40, 90],
       [57, 96, 94, 67, 98, 12, 66, 62, 44, 97],
       [69, 46, 53, 18, 43, 73, 48, 73, 41, 42],
       [23, 20, 76, 81, 50, 64, 38, 30,  8, 13]], dtype=int32)

In [20]:
arr3[::-1]

array([[36, 79, 67,  3, 67, 97, 79, 90, 36, 47],
       [77, 15, 52, 53, 60, 49,  8, 50, 49, 49],
       [23, 20, 76, 81, 50, 64, 38, 30,  8, 13],
       [69, 46, 53, 18, 43, 73, 48, 73, 41, 42],
       [57, 96, 94, 67, 98, 12, 66, 62, 44, 97],
       [62, 49,  5, 34, 96, 19, 59, 73, 40, 90],
       [ 8, 60, 11, 70,  3, 76, 26, 63, 95, 61],
       [55, 53, 56, 73, 23, 65, 91,  5, 21, 62],
       [65, 93, 40, 14,  8, 88, 12, 79, 52, 61],
       [74, 53, 98, 80, 45, 87, 51, 11, 78, 40]], dtype=int32)

In [21]:
arr3.max()

np.int32(98)

In [22]:
arr3.mean()

np.float64(52.98)

In [23]:
arr3.sum()

np.int64(5298)

In [24]:
arr3

array([[74, 53, 98, 80, 45, 87, 51, 11, 78, 40],
       [65, 93, 40, 14,  8, 88, 12, 79, 52, 61],
       [55, 53, 56, 73, 23, 65, 91,  5, 21, 62],
       [ 8, 60, 11, 70,  3, 76, 26, 63, 95, 61],
       [62, 49,  5, 34, 96, 19, 59, 73, 40, 90],
       [57, 96, 94, 67, 98, 12, 66, 62, 44, 97],
       [69, 46, 53, 18, 43, 73, 48, 73, 41, 42],
       [23, 20, 76, 81, 50, 64, 38, 30,  8, 13],
       [77, 15, 52, 53, 60, 49,  8, 50, 49, 49],
       [36, 79, 67,  3, 67, 97, 79, 90, 36, 47]], dtype=int32)

In [25]:
arr3

array([[74, 53, 98, 80, 45, 87, 51, 11, 78, 40],
       [65, 93, 40, 14,  8, 88, 12, 79, 52, 61],
       [55, 53, 56, 73, 23, 65, 91,  5, 21, 62],
       [ 8, 60, 11, 70,  3, 76, 26, 63, 95, 61],
       [62, 49,  5, 34, 96, 19, 59, 73, 40, 90],
       [57, 96, 94, 67, 98, 12, 66, 62, 44, 97],
       [69, 46, 53, 18, 43, 73, 48, 73, 41, 42],
       [23, 20, 76, 81, 50, 64, 38, 30,  8, 13],
       [77, 15, 52, 53, 60, 49,  8, 50, 49, 49],
       [36, 79, 67,  3, 67, 97, 79, 90, 36, 47]], dtype=int32)

In [26]:
arr3

array([[74, 53, 98, 80, 45, 87, 51, 11, 78, 40],
       [65, 93, 40, 14,  8, 88, 12, 79, 52, 61],
       [55, 53, 56, 73, 23, 65, 91,  5, 21, 62],
       [ 8, 60, 11, 70,  3, 76, 26, 63, 95, 61],
       [62, 49,  5, 34, 96, 19, 59, 73, 40, 90],
       [57, 96, 94, 67, 98, 12, 66, 62, 44, 97],
       [69, 46, 53, 18, 43, 73, 48, 73, 41, 42],
       [23, 20, 76, 81, 50, 64, 38, 30,  8, 13],
       [77, 15, 52, 53, 60, 49,  8, 50, 49, 49],
       [36, 79, 67,  3, 67, 97, 79, 90, 36, 47]], dtype=int32)

In [27]:
arr3.shape

(10, 10)

In [29]:
arr4=np.random.randint(1,50,(5,10))
arr4

array([[40, 39, 23,  5, 24, 24, 37,  1, 46, 43],
       [34, 27, 40, 22, 40, 39, 32, 28, 24, 26],
       [ 2, 43, 41,  8, 35, 17, 25, 48, 17, 46],
       [39, 18, 12, 27, 23, 41, 28,  3, 47,  1],
       [10,  2,  2, 29, 38, 18, 24, 19, 32,  6]], dtype=int32)