In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([1,2,33,4,4,53])

array([ 1,  2, 33,  4,  4, 53])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((10,10) , dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
np.random.rand(10)

array([0.52259379, 0.63809085, 0.1298407 , 0.36617625, 0.16556911,
       0.03176854, 0.0853435 , 0.11222067, 0.59231128, 0.77932467])

In [9]:
arr=np.random.randint(1,100,(3,3))

In [10]:
type(arr.shape)

tuple

In [11]:
print(arr.reshape(9,1,copy=True))
print(arr)

[[27]
 [69]
 [37]
 [36]
 [54]
 [73]
 [61]
 [15]
 [13]]
[[27 69 37]
 [36 54 73]
 [61 15 13]]


In [12]:
arr[:]

array([[27, 69, 37],
       [36, 54, 73],
       [61, 15, 13]], dtype=int32)

In [13]:
arr[:,-2:-1]

array([[69],
       [54],
       [15]], dtype=int32)

In [14]:
arr[1:3, 0:2]

array([[36, 54],
       [61, 15]], dtype=int32)

In [15]:
arr3=np.random.randint(1,100,(10,10))
arr3

array([[31, 73, 36, 76, 86, 61,  8, 79, 87, 75],
       [22, 47, 69, 39, 27, 43, 59,  5, 44, 73],
       [ 9, 93, 81, 44, 20, 91, 54, 75,  1,  7],
       [15, 80, 18,  3, 76, 72, 79, 59, 70,  4],
       [92, 69, 16, 13, 85,  4, 41, 99, 89, 10],
       [62, 87, 85, 78, 72,  2, 36, 78, 92, 15],
       [45, 72, 92, 66, 54, 75, 88, 49, 79, 22],
       [22, 47, 87, 10, 28, 65, 94, 61, 40,  6],
       [69, 94, 76, 61, 14,  9, 10, 61, 33, 63],
       [32, 68, 76, 13, 65, 96, 61, 44, 54,  8]], dtype=int32)

In [16]:
arr3[(arr3>50) | (arr3==67)]

array([73, 76, 86, 61, 79, 87, 75, 69, 59, 73, 93, 81, 91, 54, 75, 80, 76,
       72, 79, 59, 70, 92, 69, 85, 99, 89, 62, 87, 85, 78, 72, 78, 92, 72,
       92, 66, 54, 75, 88, 79, 87, 65, 94, 61, 69, 94, 76, 61, 61, 63, 68,
       76, 65, 96, 61, 54], dtype=int32)

In [17]:
arr3[0,0]

np.int32(31)

In [18]:
arr3[0, 5:10]

array([61,  8, 79, 87, 75], dtype=int32)

In [19]:
arr3[0:-2]

array([[31, 73, 36, 76, 86, 61,  8, 79, 87, 75],
       [22, 47, 69, 39, 27, 43, 59,  5, 44, 73],
       [ 9, 93, 81, 44, 20, 91, 54, 75,  1,  7],
       [15, 80, 18,  3, 76, 72, 79, 59, 70,  4],
       [92, 69, 16, 13, 85,  4, 41, 99, 89, 10],
       [62, 87, 85, 78, 72,  2, 36, 78, 92, 15],
       [45, 72, 92, 66, 54, 75, 88, 49, 79, 22],
       [22, 47, 87, 10, 28, 65, 94, 61, 40,  6]], dtype=int32)

In [20]:
arr3[::-1]

array([[32, 68, 76, 13, 65, 96, 61, 44, 54,  8],
       [69, 94, 76, 61, 14,  9, 10, 61, 33, 63],
       [22, 47, 87, 10, 28, 65, 94, 61, 40,  6],
       [45, 72, 92, 66, 54, 75, 88, 49, 79, 22],
       [62, 87, 85, 78, 72,  2, 36, 78, 92, 15],
       [92, 69, 16, 13, 85,  4, 41, 99, 89, 10],
       [15, 80, 18,  3, 76, 72, 79, 59, 70,  4],
       [ 9, 93, 81, 44, 20, 91, 54, 75,  1,  7],
       [22, 47, 69, 39, 27, 43, 59,  5, 44, 73],
       [31, 73, 36, 76, 86, 61,  8, 79, 87, 75]], dtype=int32)

In [21]:
arr3.max()

np.int32(99)

In [22]:
arr3.mean()

np.float64(52.25)

In [23]:
arr3.sum()

np.int64(5225)

In [24]:
arr3

array([[31, 73, 36, 76, 86, 61,  8, 79, 87, 75],
       [22, 47, 69, 39, 27, 43, 59,  5, 44, 73],
       [ 9, 93, 81, 44, 20, 91, 54, 75,  1,  7],
       [15, 80, 18,  3, 76, 72, 79, 59, 70,  4],
       [92, 69, 16, 13, 85,  4, 41, 99, 89, 10],
       [62, 87, 85, 78, 72,  2, 36, 78, 92, 15],
       [45, 72, 92, 66, 54, 75, 88, 49, 79, 22],
       [22, 47, 87, 10, 28, 65, 94, 61, 40,  6],
       [69, 94, 76, 61, 14,  9, 10, 61, 33, 63],
       [32, 68, 76, 13, 65, 96, 61, 44, 54,  8]], dtype=int32)

In [25]:
arr3

array([[31, 73, 36, 76, 86, 61,  8, 79, 87, 75],
       [22, 47, 69, 39, 27, 43, 59,  5, 44, 73],
       [ 9, 93, 81, 44, 20, 91, 54, 75,  1,  7],
       [15, 80, 18,  3, 76, 72, 79, 59, 70,  4],
       [92, 69, 16, 13, 85,  4, 41, 99, 89, 10],
       [62, 87, 85, 78, 72,  2, 36, 78, 92, 15],
       [45, 72, 92, 66, 54, 75, 88, 49, 79, 22],
       [22, 47, 87, 10, 28, 65, 94, 61, 40,  6],
       [69, 94, 76, 61, 14,  9, 10, 61, 33, 63],
       [32, 68, 76, 13, 65, 96, 61, 44, 54,  8]], dtype=int32)

In [26]:
arr3

array([[31, 73, 36, 76, 86, 61,  8, 79, 87, 75],
       [22, 47, 69, 39, 27, 43, 59,  5, 44, 73],
       [ 9, 93, 81, 44, 20, 91, 54, 75,  1,  7],
       [15, 80, 18,  3, 76, 72, 79, 59, 70,  4],
       [92, 69, 16, 13, 85,  4, 41, 99, 89, 10],
       [62, 87, 85, 78, 72,  2, 36, 78, 92, 15],
       [45, 72, 92, 66, 54, 75, 88, 49, 79, 22],
       [22, 47, 87, 10, 28, 65, 94, 61, 40,  6],
       [69, 94, 76, 61, 14,  9, 10, 61, 33, 63],
       [32, 68, 76, 13, 65, 96, 61, 44, 54,  8]], dtype=int32)

In [27]:
arr3.shape

(10, 10)